### ISSUE TITLE
Issue with Kotlin internal error

### ISSUE THREAD

**Issue by jessebridge** [aseigneurin/kafka-tutorial-kafka-h2o#1]
Hi i cloned your repo to understand the workings of Kafka and h20, however when i try to run consumeandpredict.kt it gives me a kotlin internal error of java.lang.AbstractMethodError. Have you experience this before? and if so how did you over come this issue. 
Cheers - Jesse

**Comment by aseigneurin** [comment]
Hi,
I’d say there’s a conflict of versions: some classes expect a given version of a library but a newer or an older version is provided instead. 
Maybe a different version of the H2O library than the one I originally used?
Send the stack trace and I could confirm that.

**Comment by jessebridge** [comment]
I had to change the version of kotlin Intellij was using as the gradle file was after a version that wasnt installed/available with intellij. So now it is running, however now there are issues when running the code it produces these errors in the console :

18/11/26 11:09:33.012 WARN org.apache.kafka.clients.NetworkClient: [Consumer clientId=kafka-tutorial-3e5aafad-83a2-4f16-b411-3af126256619-StreamThread-1-consumer, groupId=kafka-tutorial] Connection to node -1 could not be established. Broker may not be available.

18/11/26 11:09:34.301 WARN org.apache.kafka.clients.NetworkClient: [AdminClient clientId=kafka-tutorial-3e5aafad-83a2-4f16-b411-3af126256619-admin] Connection to node -1 could not be established. Broker may not be available.

and the same errors appear in the command line when trying to run:
kafka-console-consumer --bootstrap-server localhost:9092 --topic housing

**Comment by aseigneurin** [comment]
Glad you fixed the error. 
For the other error, I suppose you Kafka is running on your machine. Maybe replace “localhost” with “127.0.0.1” or “0.0.0.0”?

**Comment by jessebridge** [comment]
Apologies i had a mind blank and didnt realise i wasnt running zookeeper or kafka just yet... missed some steps is all. This is all new to me but im looking to learn! i am now able to run the Consume and predict file in the src files. However when i set up the listener using -
 kafka-console-consumer --bootstrap-server localhost:9092 --topic housing

It returns [2018-11-26 11:35:42,107] WARN [Consumer clientId=consumer-1, groupId=console-consumer-89974] Error while fetching metadata with correlation id 2 : {housing=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

[2018-11-26 11:35:42,151] WARN [Consumer clientId=consumer-1, groupId=console-consumer-89974] Error while fetching metadata with correlation id 6 : {housing=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

[2018-11-26 11:35:42,157] WARN [Consumer clientId=consumer-1, groupId=console-consumer-89974] The following subscribed topics are not assigned to any members: [housing]  (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)

**Comment by aseigneurin** [comment]
Hm, did you create the topic prior to using it?

**Comment by jessebridge** [comment]
No i dont believe i did, i thought that was possibly part of the code that was writtien. My mistake. It's this line here to create the topic? 

kafka-topics --zookeeper localhost:2181 --create --topic housing --replication-factor 1 --partitions 4

**Comment by aseigneurin** [comment]
Yes, that line is a reminder of the command to run to create the topic prior to running the code.

**Comment by jessebridge** [comment]
Hmm, i have the zookeeper server running, the kafka server running, the topic is created, the consumer is running using 'kafka-console-consumer.bat --bootstrap-server localhost:9092 --topic predictions' and i am running the ConsumeandPredict code in intellij however the consumer is not recieveing the outputs. Is there anything else i need to have running?

**Comment by jessebridge** [comment]
The code console is sitting here: 

18/11/26 12:25:25.724 INFO org.apache.kafka.streams.processor.internals.StreamThread: stream-thread [kafka-tutorial-456989cd-defb-4719-a86b-8d54cc3f49af-StreamThread-1] partition assignment took 1 ms.
	current active tasks: []
	current standby tasks: []
	previous active tasks: []

18/11/26 12:25:25.790 INFO org.apache.kafka.streams.processor.internals.StreamThread: stream-thread [kafka-tutorial-456989cd-defb-4719-a86b-8d54cc3f49af-StreamThread-1] State transition from PARTITIONS_ASSIGNED to RUNNING
18/11/26 12:25:25.790 INFO org.apache.kafka.streams.KafkaStreams: stream-client [kafka-tutorial-456989cd-defb-4719-a86b-8d54cc3f49af] State transition from REBALANCING to RUNNING

**Comment by jessebridge** [comment]
NoNode for /config/topics/predictions (org.apache.zookeeper.server.PrepRequestProcessor) was found in the zookeeper comamnd prompt which might help narrow the cause

**Comment by aseigneurin** [comment]
The output of the Kafka Streams app says “Running” which looks good to me. Now you can send messages to the topic and you should see some results.

**Comment by aseigneurin** [comment]
Make sure you send data to the “housing” topic and look for results in the “predictions” topic (which needs to be created too).

**Comment by jessebridge** [comment]
All good and running now, thankyou so much! it works really well :)

**Comment by aseigneurin** [comment]
Great!
