### ISSUE TITLE
Trying to run code in command line using kotlin compiler

### ISSUE THREAD

**Issue by jessebridge** [aseigneurin/kafka-tutorial-kafka-h2o#2]
Hi sorry to be a bother, but when trying to run the code in command line using the kotlin compiler it throws  error: unresolved reference: ippontech import com.ippontech.kafkah2o.*
Which then leads to larger issues further in the code that accesses those packages. Do you happen to know of a fix?

**Comment by aseigneurin** [comment]
Hm, how are you compiling the code? What command?

Can you also paste the whole error message?

**Comment by jessebridge** [comment]
The command :  kotlinc ReadFromDbApplyMLandStoreResults.kt
i have created custom code which i am running inside the kotlin folder.


kotlinc ReadFromDbApplyMLandStoreResults.kt
ReadFromDbApplyMLandStoreResults.kt:3:12: error: unresolved reference: ippontech
import com.ippontech.kafkah2o.*
           ^
ReadFromDbApplyMLandStoreResults.kt:4:8: error: unresolved reference: hex
import hex.genmodel.easy.EasyPredictModelWrapper
       ^
ReadFromDbApplyMLandStoreResults.kt:5:8: error: unresolved reference: hex
import hex.genmodel.easy.RowData
       ^
ReadFromDbApplyMLandStoreResults.kt:15:28: error: unresolved reference: gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85
    private val rawModel = gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85()
                           ^
ReadFromDbApplyMLandStoreResults.kt:17:25: error: unresolved reference: EasyPredictModelWrapper
    private val model = EasyPredictModelWrapper(rawModel)
                        ^
ReadFromDbApplyMLandStoreResults.kt:59:31: error: unresolved reference: RowData
                    val row = RowData().apply {
                              ^
ReadFromDbApplyMLandStoreResults.kt:60:25: error: unresolved reference: put
                        put("sqft", resultset!!.getDouble("sqft"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:61:25: error: unresolved reference: put
                        put("lot_size_acres", resultset!!.getDouble("lot_size"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:62:25: error: unresolved reference: put
                        put("stories", resultset!!.getDouble("stories"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:63:25: error: unresolved reference: put
                        put("number_bedrooms", resultset!!.getDouble("number_bedrooms"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:64:25: error: unresolved reference: put
                        put("number_bathrooms", resultset!!.getDouble("number_bathrooms"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:65:25: error: unresolved reference: put
                        put("attached_garage", resultset!!.getBoolean("attached_garage").toYesNo())
                        ^
ReadFromDbApplyMLandStoreResults.kt:65:90: error: unresolved reference: toYesNo
                        put("attached_garage", resultset!!.getBoolean("attached_garage").toYesNo())
                                                                                         ^
ReadFromDbApplyMLandStoreResults.kt:66:25: error: unresolved reference: put
                        put("has_pool", resultset!!.getBoolean("has_pool").toYesNo())
                        ^
ReadFromDbApplyMLandStoreResults.kt:66:76: error: unresolved reference: toYesNo
                        put("has_pool", resultset!!.getBoolean("has_pool").toYesNo())
                                                                           ^
ReadFromDbApplyMLandStoreResults.kt:67:25: error: unresolved reference: put
                        put("has_kitchen_island", resultset!!.getBoolean("has_kitchen_island").toYesNo())
                        ^
ReadFromDbApplyMLandStoreResults.kt:67:96: error: unresolved reference: toYesNo
                        put("has_kitchen_island", resultset!!.getBoolean("has_kitchen_island").toYesNo())
                                                                                               ^
ReadFromDbApplyMLandStoreResults.kt:68:25: error: unresolved reference: put
                        put("main_flooring_type", resultset!!.getString("main_flooring_type"))
                        ^
ReadFromDbApplyMLandStoreResults.kt:69:25: error: unresolved reference: put
                        put("has_granite_counters", resultset!!.getBoolean("has_granite_counters").toYesNo())
                        ^
ReadFromDbApplyMLandStoreResults.kt:69:100: error: unresolved reference: toYesNo
                        put("has_granite_counters", resultset!!.getBoolean("has_granite_counters").toYesNo())
                                                                                                   ^
ReadFromDbApplyMLandStoreResults.kt:70:25: error: unresolved reference: put
                        put("house_age_years", resultset!!.getDouble("house_age_years"))
                        ^

**Comment by aseigneurin** [comment]
Ah, no one uses `kotlinc` or `javac` to compile code in real life ;)

Use `gradle compile` or `gradle build` from the root of the project instead.

**Comment by aseigneurin** [comment]
Or use IntelliJ.

**Comment by jessebridge** [comment]
I'm currently using Intelluj to develop in, i was just curious if it were possible to run the code in the command line. Once again thankyou for your swift and helpful response!

**Comment by aseigneurin** [comment]
A few thoughts:
- "run the code in command line using the kotlin compiler" -> there is something awkward here: you can _compile_ the code with the compiler, but then you should _run_ the code with `java`. IntelliJ already compiles the code for you, so you don't need to invoke the compiler yourself.
- Running the code without assembling a Jar is virtually impossible (IDEs do it, but you would never do it by hand).
- If you want to run the code from the command line, build the Jar (`gradle build`) then run it with `java -cp xxx.jar xxx.Main`.

**Comment by jessebridge** [comment]
Sorry to be a pain but this seems like the only way i am able to contact you at the moment, but i was curious if you happen to know how to call the POJO by a string? I am reading from a database that containst the POJO name and i want to use that string to then point to the POJO class of yours, that way i can make it more dynamic with other POJOs

**Comment by aseigneurin** [comment]
Hm, what you are explaining is not very clear and quite confusing. Send code and detailed explanations and I will see if I can help.

**Comment by jessebridge** [comment]
Apologies, I am pulling the string of the name of the POJO stored in the Java file. I am wondering if i can call that POJO just by having the string of its name. 

for example var pojoname = "blah" rawmodel = 'pojoname'(). 

Currently i am doing it statically in the code like this : 
if (POJOLink == "gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85") {
            rawModel = gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85()
            model = EasyPredictModelWrapper(rawModel)
        }

**Comment by aseigneurin** [comment]
I see. Let's not call this class a "POJO". It's a model, although H2O calls it a "model POJO". A POJO usually refers to something a bit different.

Anyways, you can create an instance of this class through reflection, if you only have the class name.

**Comment by jessebridge** [comment]
This is what i have written but it returns an error saying it cant find "gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85"

val pojoClass = Class.forName(POJOLink)
val rawModel: GenModel = pojoClass.newInstance() as GenModel
model = EasyPredictModelWrapper(rawModel)

**Comment by aseigneurin** [comment]
You need to use the class' fully qualified name.

**Comment by jessebridge** [comment]
sorry im not quite sure what you mean by that, do you mean by adding .java at the end of it? Could you provide an example

**Comment by aseigneurin** [comment]
It's the name including the package name: `com.ippontech.kafkah2o.gbm_2760b04d_9dfd_436c_b780_7bdb2f372d85`.

**Comment by jessebridge** [comment]
Absolute legend! Thankyou for your help with these issues
